version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
